User can view their entries - Sina Daryaei
sinadaryaei/code-journal- pull request #6
Opened 2023-06-01 23:28 UTC by sinadaryaei

https://github.com/sinadaryaei/code-journal-/assets/125223265/911d992b-b370-4524-acc0-4c8fb08facd7

2023-06-01 23:35 UTC, shawnkost requested changes
A few changes requested here Sina!

2023-06-01 23:35 UTC, shawnkost commented on js/main.js
> +  const entriesView = document.querySelector("[data-view='entries']");
Move these outside the function. By having them inside of here, we'd have to traverse the DOM over and over every single time this function gets called. If we move the `querySelector`s outside the function to the global space, we can just do the search one and always have a reference to them

2023-06-01 23:35 UTC, shawnkost commented on js/main.js
> +  event.preventDefault();
Not needed

2023-06-01 23:35 UTC, shawnkost commented on js/main.js
> +  event.preventDefault();
Not needed

2023-06-02 01:54 UTC, sinadaryaei commented on js/main.js
> +  event.preventDefault();
Can you please specify which lines?

2023-06-02 01:54 UTC, sinadaryaei commented on js/main.js
> +  event.preventDefault();
Can you please specify which lines?

2023-06-04 20:44 UTC, shawnkost approved these changes
👍🏻

2023-06-04 23:14 UTC, merged